spring:
  application:
    name: trade-reporting-engine
  datasource:
    username: test
    password: test
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 8
      connection-test-query: select 1
      connection-init-sql: select 1
  flyway:
    enabled: true
    out-of-order: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  pattern:
    level: "%5p [correlationId=%X{correlationId:-}]"
  level:
    per.duyd: DEBUG